name: Terraform AWS Deploy

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: "043391333434"
  TF_ACTION: "destroy"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Lambda
        working-directory: lambda
        run: mvn clean package

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_ID}}:role/Github-Actions-Terraform-Role
          aws-region: ${{env.AWS_REGION}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform ${{env.TF_ACTION}} -auto-approve