name: Terraform AWS Deploy

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: "043391333434"
  TF_ACTION: "apply"  # apply or destroy
  FUNCTION_NAME: "hello-java-lambda"
  QUEUE_NAME: "hello-queue"
  MAPPING_UUID_TRIGGER: "5f76a14f-6b06-4145-99b2-07e10e7be6bd"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
        # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

        # Configure AWS credentials using OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_ID}}:role/Github-Actions-Terraform-Role
          aws-region: ${{env.AWS_REGION}}

        # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

        # Setup Java (não é necessário para destroy, mas mantido)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

        # Initialize Terraform
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

        # Build the Lambda function
      - name: Build Lambda
        working-directory: lambda
        run: mvn clean package

        #########################################
        ## DESTROY FLOW
        #########################################


        ################ LAMBDA ################

        # Import existing Lambda function in state if destroying
      - name: Terraform Import Lambda
        if: env.TF_ACTION == 'destroy'
        working-directory: terraform
        run: |
          FUNCTION_NAME=${{env.FUNCTION_NAME}}
          echo "✅ Importando FUNCTION LAMBDA"
          terraform import aws_lambda_function.hello_lambda hello-java-lambda

        # Validate Lambda import (state + AWS)
      - name: Validate Lambda Import
        if: env.TF_ACTION == 'destroy'
        working-directory: terraform
        run: |
          FUNCTION_NAME=${{env.FUNCTION_NAME}}

          # valida state
          terraform state list | grep -q aws_lambda_function.hello_lambda || {
            echo "❌ Lambda não está no state"
            exit 1
          }

          # valida AWS
          if aws lambda get-function --function-name "$FUNCTION_NAME" >/dev/null 2>&1; then
            echo "✅ Lambda importada com sucesso e existe na AWS"
          else
            echo "❌ Lambda não existe na AWS"
            exit 1
          fi

        ################ SQS ################

        # Import existing SQS queue in state if destroying
      - name: Terraform Import SQS
        if: env.TF_ACTION == 'destroy'
        working-directory: terraform
        run: |
          QUEUE_NAME=${{env.QUEUE_NAME}}

          QUEUE_URL=$(aws sqs get-queue-url \
            --queue-name "$QUEUE_NAME" \
            --query 'QueueUrl' \
            --output text)

          echo "✅ Importando SQS: $QUEUE_URL"

          terraform import aws_sqs_queue.hello_queue "$QUEUE_URL"

        # Validate SQS import (state + AWS)
      - name: Validate SQS Import
        if: env.TF_ACTION == 'destroy'
        working-directory: terraform
        run: |
          QUEUE_NAME=${{env.QUEUE_NAME}}

          # valida state
          terraform state list | grep -q aws_sqs_queue.hello_queue || {
            echo "❌ SQS não está no state"
            exit 1
          }

          # valida AWS
          if aws sqs get-queue-url --queue-name "$QUEUE_NAME" >/dev/null 2>&1; then
            echo "✅ SQS importada com sucesso e existe na AWS"
          else
            echo "❌ SQS não existe na AWS"
            exit 1
          fi

        ################ TRIGGER LAMBDA + SQS ################

        # Import existing Lambda SQS Trigger in state if destroying
      - name: Terraform Import Lambda SQS Trigger
        if: env.TF_ACTION == 'destroy'
        working-directory: terraform
        run: |
          MAPPING_UUID=${{env.MAPPING_UUID_TRIGGER}}
          echo "✅ Importando Lambda SQS Trigger"
          terraform import \
            aws_lambda_event_source_mapping.sqs_trigger \
            "$MAPPING_UUID"

        ################ SNS ################

        # Import existing SNS in state if destroying
      - name: Terraform import SNS
        if: env.TF_ACTION == 'destroy'
        working-directory: terraform
        run: |
          TOPIC_ARN="arn:aws:sns:${{env.AWS_REGION}}:${{env.AWS_ACCOUNT_ID}}:hello-java-sns-topic"
          echo "✅ Importando SNS topic"
          terraform import aws_sns_topic.hello_topic "$TOPIC_ARN"

        # Validate SNS import (state + AWS)
      - name: Validate SNS Import
        if: env.TF_ACTION == 'destroy'
        working-directory: terraform
        run: |
          TOPIC_ARN="arn:aws:sns:${{env.AWS_REGION}}:${{env.AWS_ACCOUNT_ID}}:hello-java-sns-topic"

          # valida state
          terraform state list | grep -q aws_sns_topic.hello_topic || {
            echo "❌ SNS não está no state"
            exit 1
          }

          # valida AWS
          if aws sns get-topic-attributes --topic-arn "$TOPIC_ARN" >/dev/null 2>&1; then
            echo "✅ SNS importada com sucesso e existe na AWS"
          else
            echo "❌ SNS não existe na AWS"
            exit 1
          fi
          

        #########################################
        ## END DESTROY FLOW
        #########################################

        # Generate Terraform plan (opcional no destroy)
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

        # Apply or Destroy Terraform resources
      - name: Terraform Apply/Destroy
        working-directory: terraform
        run: terraform ${{env.TF_ACTION}} -auto-approve

        ########################################
        ## VALIDATIONS AFTER DESTROY IN AWS
        ########################################

        # Validate the SQS queue is destroyed
      - name: Validate SQS Destroyed
        if: env.TF_ACTION == 'destroy'
        run: |
          QUEUE_NAME=${{env.QUEUE_NAME}}

          RESULT=$(aws sqs list-queues --queue-name-prefix "$QUEUE_NAME")

          if echo "$RESULT" | grep -q "$QUEUE_NAME"; then
            echo "❌ SQS ainda existe na AWS"
            exit 1
          else
            echo "✅ SQS destruída com sucesso"
          fi

        # Validate the Lambda function is destroyed
      - name: Validate Lambda Destroyed
        if: env.TF_ACTION == 'destroy'
        run: |
          FUNCTION_NAME=${{env.FUNCTION_NAME}}

          if aws lambda get-function --function-name "$FUNCTION_NAME" >/dev/null 2>&1; then
            echo "❌ Lambda ainda existe na AWS"
            exit 1
          else
            echo "✅ Lambda destruída com sucesso"
          fi

        # Validate the SNS topic is destroyed
      - name: Validate SNS Destroyed
        if: env.TF_ACTION == 'destroy'
        run: |
          TOPIC_ARN="arn:aws:sns:${{env.AWS_REGION}}:${{env.AWS_ACCOUNT_ID}}:hello-java-sns-topic"

          if aws sns get-topic-attributes --topic-arn "$TOPIC_ARN" >/dev/null 2>&1; then
            echo "❌ SNS ainda existe na AWS"
            exit 1
          else
            echo "✅ SNS destruída com sucesso"
          fi

        # Validate the Lambda SQS Trigger is destroyed
      - name: Validate Lambda SQS Trigger Destroyed
        if: env.TF_ACTION == 'destroy'
        run: |
          MAPPING_UUID=${{env.MAPPING_UUID_TRIGGER}}

          if aws lambda get-event-source-mapping --uuid "$MAPPING_UUID" >/dev/null 2>&1; then
            echo "❌ Lambda SQS Trigger ainda existe na AWS"
            exit 1
          else
            echo "✅ Lambda SQS Trigger destruída com sucesso"
          fi